
// ===== RUTAS INTERNACIONALES INVERSAS (WORLD → USA) =====
// Generadas automáticamente - 2025-10-17
const INTERNATIONAL_REVERSE_ROUTES: SimulatedRoute[] = [
  { from: "BOG", to: "JFK", airline: "American Airlines", airlineCode: "AA", basePrice: 450, duration: "5h 30m", typical_flights_per_day: 5, countries: { from: "Colombia", to: "USA" } },
  { from: "BOG", to: "MIA", airline: "American Airlines", airlineCode: "AA", basePrice: 450, duration: "5h 30m", typical_flights_per_day: 5, countries: { from: "Colombia", to: "USA" } },
  { from: "BOG", to: "DFW", airline: "American Airlines", airlineCode: "AA", basePrice: 450, duration: "5h 30m", typical_flights_per_day: 5, countries: { from: "Colombia", to: "USA" } },
  { from: "MDE", to: "MIA", airline: "American Airlines", airlineCode: "AA", basePrice: 400, duration: "4h 0m", typical_flights_per_day: 4, countries: { from: "Colombia", to: "USA" } },
  { from: "GRU", to: "JFK", airline: "American Airlines", airlineCode: "AA", basePrice: 650, duration: "10h 15m", typical_flights_per_day: 4, countries: { from: "Brazil", to: "USA" } },
  { from: "GRU", to: "MIA", airline: "American Airlines", airlineCode: "AA", basePrice: 650, duration: "10h 15m", typical_flights_per_day: 4, countries: { from: "Brazil", to: "USA" } },
  { from: "GRU", to: "DFW", airline: "American Airlines", airlineCode: "AA", basePrice: 650, duration: "10h 15m", typical_flights_per_day: 4, countries: { from: "Brazil", to: "USA" } },
  { from: "GIG", to: "MIA", airline: "American Airlines", airlineCode: "AA", basePrice: 580, duration: "8h 55m", typical_flights_per_day: 4, countries: { from: "Brazil", to: "USA" } },
  { from: "EZE", to: "JFK", airline: "American Airlines", airlineCode: "AA", basePrice: 700, duration: "10h 50m", typical_flights_per_day: 4, countries: { from: "Argentina", to: "USA" } },
  { from: "EZE", to: "MIA", airline: "American Airlines", airlineCode: "AA", basePrice: 700, duration: "10h 50m", typical_flights_per_day: 4, countries: { from: "Argentina", to: "USA" } },
  { from: "SCL", to: "MIA", airline: "American Airlines", airlineCode: "AA", basePrice: 680, duration: "9h 45m", typical_flights_per_day: 4, countries: { from: "Chile", to: "USA" } },
  { from: "SCL", to: "DFW", airline: "American Airlines", airlineCode: "AA", basePrice: 720, duration: "10h 30m", typical_flights_per_day: 4, countries: { from: "Chile", to: "USA" } },
  { from: "LIM", to: "JFK", airline: "American Airlines", airlineCode: "AA", basePrice: 500, duration: "8h 15m", typical_flights_per_day: 4, countries: { from: "Peru", to: "USA" } },
  { from: "LIM", to: "MIA", airline: "American Airlines", airlineCode: "AA", basePrice: 450, duration: "6h 35m", typical_flights_per_day: 4, countries: { from: "Peru", to: "USA" } },
  { from: "UIO", to: "MIA", airline: "American Airlines", airlineCode: "AA", basePrice: 480, duration: "5h 25m", typical_flights_per_day: 3, countries: { from: "Ecuador", to: "USA" } },
  { from: "UIO", to: "DFW", airline: "American Airlines", airlineCode: "AA", basePrice: 520, duration: "7h 10m", typical_flights_per_day: 3, countries: { from: "Ecuador", to: "USA" } },
  { from: "YYZ", to: "JFK", airline: "Porter Airlines", airlineCode: "PD", basePrice: 220, duration: "1h 45m", typical_flights_per_day: 6, countries: { from: "Canada", to: "USA" } },
  { from: "YYZ", to: "BOS", airline: "Porter Airlines", airlineCode: "PD", basePrice: 210, duration: "1h 50m", typical_flights_per_day: 4, countries: { from: "Canada", to: "USA" } },
  { from: "YVR", to: "LAX", airline: "Alaska Airlines", airlineCode: "AS", basePrice: 240, duration: "2h 50m", typical_flights_per_day: 8, countries: { from: "Canada", to: "USA" } },
  { from: "YVR", to: "SEA", airline: "Alaska Airlines", airlineCode: "AS", basePrice: 150, duration: "1h 0m", typical_flights_per_day: 12, countries: { from: "Canada", to: "USA" } },
  { from: "YUL", to: "JFK", airline: "Porter Airlines", airlineCode: "PD", basePrice: 210, duration: "1h 30m", typical_flights_per_day: 4, countries: { from: "Canada", to: "USA" } },
  { from: "YUL", to: "LAX", airline: "American Airlines", airlineCode: "AA", basePrice: 420, duration: "5h 45m", typical_flights_per_day: 2, countries: { from: "Canada", to: "USA" } },
  { from: "YYC", to: "JFK", airline: "Porter Airlines", airlineCode: "PD", basePrice: 280, duration: "2h 50m", typical_flights_per_day: 4, countries: { from: "Canada", to: "USA" } },
  { from: "YYC", to: "LAX", airline: "Alaska Airlines", airlineCode: "AS", basePrice: 280, duration: "2h 45m", typical_flights_per_day: 6, countries: { from: "Canada", to: "USA" } },
  { from: "YYC", to: "SEA", airline: "Alaska Airlines", airlineCode: "AS", basePrice: 180, duration: "1h 30m", typical_flights_per_day: 8, countries: { from: "Canada", to: "USA" } },
  { from: "MEX", to: "JFK", airline: "American Airlines", airlineCode: "AA", basePrice: 380, duration: "5h 15m", typical_flights_per_day: 3, countries: { from: "Mexico", to: "USA" } },
  { from: "MEX", to: "MIA", airline: "American Airlines", airlineCode: "AA", basePrice: 330, duration: "3h 25m", typical_flights_per_day: 4, countries: { from: "Mexico", to: "USA" } },
  { from: "MEX", to: "DFW", airline: "American Airlines", airlineCode: "AA", basePrice: 280, duration: "2h 45m", typical_flights_per_day: 8, countries: { from: "Mexico", to: "USA" } },
  { from: "MEX", to: "LAX", airline: "American Airlines", airlineCode: "AA", basePrice: 340, duration: "4h 10m", typical_flights_per_day: 6, countries: { from: "Mexico", to: "USA" } },
  { from: "CUN", to: "MIA", airline: "American Airlines", airlineCode: "AA", basePrice: 280, duration: "2h 10m", typical_flights_per_day: 6, countries: { from: "Mexico", to: "USA" } },
  { from: "CUN", to: "DFW", airline: "American Airlines", airlineCode: "AA", basePrice: 320, duration: "3h 20m", typical_flights_per_day: 4, countries: { from: "Mexico", to: "USA" } },
  { from: "SJO", to: "MIA", airline: "American Airlines", airlineCode: "AA", basePrice: 320, duration: "3h 10m", typical_flights_per_day: 4, countries: { from: "Costa Rica", to: "USA" } },
  { from: "SJO", to: "DFW", airline: "American Airlines", airlineCode: "AA", basePrice: 360, duration: "4h 25m", typical_flights_per_day: 2, countries: { from: "Costa Rica", to: "USA" } },
  { from: "PTY", to: "MIA", airline: "American Airlines", airlineCode: "AA", basePrice: 340, duration: "3h 20m", typical_flights_per_day: 4, countries: { from: "Panama", to: "USA" } },
  { from: "PTY", to: "DFW", airline: "American Airlines", airlineCode: "AA", basePrice: 380, duration: "4h 35m", typical_flights_per_day: 2, countries: { from: "Panama", to: "USA" } },
  { from: "SDQ", to: "MIA", airline: "American Airlines", airlineCode: "AA", basePrice: 280, duration: "2h 35m", typical_flights_per_day: 4, countries: { from: "Dominican Republic", to: "USA" } },
  { from: "SDQ", to: "JFK", airline: "American Airlines", airlineCode: "AA", basePrice: 320, duration: "3h 55m", typical_flights_per_day: 2, countries: { from: "Dominican Republic", to: "USA" } },
  { from: "PUJ", to: "MIA", airline: "American Airlines", airlineCode: "AA", basePrice: 290, duration: "2h 25m", typical_flights_per_day: 6, countries: { from: "Dominican Republic", to: "USA" } },
  { from: "PUJ", to: "JFK", airline: "American Airlines", airlineCode: "AA", basePrice: 330, duration: "3h 50m", typical_flights_per_day: 3, countries: { from: "Dominican Republic", to: "USA" } },
  { from: "LHR", to: "JFK", airline: "American Airlines", airlineCode: "AA", basePrice: 550, duration: "7h 15m", typical_flights_per_day: 7, countries: { from: "United Kingdom", to: "USA" } },
  { from: "LHR", to: "BOS", airline: "American Airlines", airlineCode: "AA", basePrice: 550, duration: "7h 15m", typical_flights_per_day: 7, countries: { from: "United Kingdom", to: "USA" } },
  { from: "LHR", to: "PHL", airline: "American Airlines", airlineCode: "AA", basePrice: 550, duration: "7h 15m", typical_flights_per_day: 7, countries: { from: "United Kingdom", to: "USA" } },
  { from: "LHR", to: "LAX", airline: "American Airlines", airlineCode: "AA", basePrice: 550, duration: "7h 15m", typical_flights_per_day: 7, countries: { from: "United Kingdom", to: "USA" } },
  { from: "DUB", to: "JFK", airline: "Aer Lingus", airlineCode: "EI", basePrice: 520, duration: "6h 50m", typical_flights_per_day: 5, countries: { from: "Ireland", to: "USA" } },
  { from: "DUB", to: "BOS", airline: "Aer Lingus", airlineCode: "EI", basePrice: 520, duration: "6h 50m", typical_flights_per_day: 5, countries: { from: "Ireland", to: "USA" } },
  { from: "DUB", to: "LAX", airline: "Aer Lingus", airlineCode: "EI", basePrice: 520, duration: "6h 50m", typical_flights_per_day: 5, countries: { from: "Ireland", to: "USA" } },
  { from: "EDI", to: "JFK", airline: "Aer Lingus", airlineCode: "EI", basePrice: 540, duration: "7h 5m", typical_flights_per_day: 4, countries: { from: "United Kingdom", to: "USA" } },
  { from: "EDI", to: "LAX", airline: "British Airways", airlineCode: "BA", basePrice: 650, duration: "10h 50m", typical_flights_per_day: 4, countries: { from: "United Kingdom", to: "USA" } },
  { from: "CDG", to: "JFK", airline: "Aer Lingus", airlineCode: "EI", basePrice: 570, duration: "7h 55m", typical_flights_per_day: 6, countries: { from: "France", to: "USA" } },
  { from: "CDG", to: "BOS", airline: "Aer Lingus", airlineCode: "EI", basePrice: 570, duration: "7h 55m", typical_flights_per_day: 6, countries: { from: "France", to: "USA" } },
  { from: "CDG", to: "LAX", airline: "American Airlines", airlineCode: "AA", basePrice: 640, duration: "11h 15m", typical_flights_per_day: 6, countries: { from: "France", to: "USA" } },
  { from: "MUC", to: "JFK", airline: "British Airways", airlineCode: "BA", basePrice: 600, duration: "8h 30m", typical_flights_per_day: 4, countries: { from: "Germany", to: "USA" } },
  { from: "MUC", to: "LAX", airline: "American Airlines", airlineCode: "AA", basePrice: 680, duration: "11h 45m", typical_flights_per_day: 4, countries: { from: "Germany", to: "USA" } },
  { from: "MAD", to: "JFK", airline: "American Airlines", airlineCode: "AA", basePrice: 560, duration: "7h 45m", typical_flights_per_day: 6, countries: { from: "Spain", to: "USA" } },
  { from: "MAD", to: "MIA", airline: "American Airlines", airlineCode: "AA", basePrice: 560, duration: "7h 45m", typical_flights_per_day: 6, countries: { from: "Spain", to: "USA" } },
  { from: "BCN", to: "JFK", airline: "American Airlines", airlineCode: "AA", basePrice: 580, duration: "8h 0m", typical_flights_per_day: 5, countries: { from: "Spain", to: "USA" } },
  { from: "FCO", to: "JFK", airline: "British Airways", airlineCode: "BA", basePrice: 590, duration: "8h 50m", typical_flights_per_day: 5, countries: { from: "Italy", to: "USA" } },
  { from: "FCO", to: "LAX", airline: "American Airlines", airlineCode: "AA", basePrice: 670, duration: "12h 20m", typical_flights_per_day: 5, countries: { from: "Italy", to: "USA" } },
  { from: "MXP", to: "JFK", airline: "British Airways", airlineCode: "BA", basePrice: 580, duration: "8h 40m", typical_flights_per_day: 4, countries: { from: "Italy", to: "USA" } },
  { from: "MXP", to: "LAX", airline: "American Airlines", airlineCode: "AA", basePrice: 660, duration: "12h 10m", typical_flights_per_day: 4, countries: { from: "Italy", to: "USA" } },
  { from: "AMS", to: "JFK", airline: "British Airways", airlineCode: "BA", basePrice: 580, duration: "7h 50m", typical_flights_per_day: 5, countries: { from: "Netherlands", to: "USA" } },
  { from: "AMS", to: "LAX", airline: "American Airlines", airlineCode: "AA", basePrice: 650, duration: "11h 20m", typical_flights_per_day: 5, countries: { from: "Netherlands", to: "USA" } },
  { from: "ZRH", to: "JFK", airline: "British Airways", airlineCode: "BA", basePrice: 600, duration: "8h 15m", typical_flights_per_day: 4, countries: { from: "Switzerland", to: "USA" } },
  { from: "ZRH", to: "LAX", airline: "American Airlines", airlineCode: "AA", basePrice: 680, duration: "11h 50m", typical_flights_per_day: 4, countries: { from: "Switzerland", to: "USA" } },
  { from: "GVA", to: "JFK", airline: "British Airways", airlineCode: "BA", basePrice: 590, duration: "8h 5m", typical_flights_per_day: 4, countries: { from: "Switzerland", to: "USA" } },
  { from: "GVA", to: "LAX", airline: "American Airlines", airlineCode: "AA", basePrice: 670, duration: "11h 40m", typical_flights_per_day: 4, countries: { from: "Switzerland", to: "USA" } },
  { from: "LIS", to: "JFK", airline: "British Airways", airlineCode: "BA", basePrice: 570, duration: "7h 30m", typical_flights_per_day: 4, countries: { from: "Portugal", to: "USA" } },
  { from: "LIS", to: "LAX", airline: "American Airlines", airlineCode: "AA", basePrice: 660, duration: "12h 0m", typical_flights_per_day: 4, countries: { from: "Portugal", to: "USA" } },
  { from: "ATH", to: "JFK", airline: "British Airways", airlineCode: "BA", basePrice: 620, duration: "10h 15m", typical_flights_per_day: 4, countries: { from: "Greece", to: "USA" } },
  { from: "ATH", to: "LAX", airline: "American Airlines", airlineCode: "AA", basePrice: 720, duration: "14h 30m", typical_flights_per_day: 4, countries: { from: "Greece", to: "USA" } },
  { from: "CPH", to: "JFK", airline: "Finnair", airlineCode: "AY", basePrice: 610, duration: "8h 20m", typical_flights_per_day: 4, countries: { from: "Denmark", to: "USA" } },
  { from: "CPH", to: "LAX", airline: "Qatar Airways", airlineCode: "QR", basePrice: 880, duration: "17h 45m", typical_flights_per_day: 4, countries: { from: "Denmark", to: "USA" } },
  { from: "ARN", to: "JFK", airline: "British Airways", airlineCode: "BA", basePrice: 630, duration: "8h 45m", typical_flights_per_day: 3, countries: { from: "Sweden", to: "USA" } },
  { from: "ARN", to: "LAX", airline: "Icelandair", airlineCode: "FI", basePrice: 700, duration: "12h 30m", typical_flights_per_day: 3, countries: { from: "Sweden", to: "USA" } },
  { from: "OSL", to: "JFK", airline: "Icelandair", airlineCode: "FI", basePrice: 620, duration: "8h 30m", typical_flights_per_day: 3, countries: { from: "Norway", to: "USA" } },
  { from: "OSL", to: "LAX", airline: "Icelandair", airlineCode: "FI", basePrice: 690, duration: "12h 15m", typical_flights_per_day: 3, countries: { from: "Norway", to: "USA" } },
  { from: "HEL", to: "JFK", airline: "Icelandair", airlineCode: "FI", basePrice: 650, duration: "8h 45m", typical_flights_per_day: 3, countries: { from: "Finland", to: "USA" } },
  { from: "HEL", to: "LAX", airline: "Icelandair", airlineCode: "FI", basePrice: 720, duration: "13h 0m", typical_flights_per_day: 3, countries: { from: "Finland", to: "USA" } },
  { from: "WAW", to: "JFK", airline: "Qatar Airways", airlineCode: "QR", basePrice: 750, duration: "16h 45m", typical_flights_per_day: 3, countries: { from: "Poland", to: "USA" } },
  { from: "WAW", to: "LAX", airline: "Qatar Airways", airlineCode: "QR", basePrice: 850, duration: "20h 30m", typical_flights_per_day: 3, countries: { from: "Poland", to: "USA" } },
  { from: "PRG", to: "JFK", airline: "Condor", airlineCode: "DE", basePrice: 620, duration: "9h 0m", typical_flights_per_day: 3, countries: { from: "Czech Republic", to: "USA" } },
  { from: "PRG", to: "LAX", airline: "Condor", airlineCode: "DE", basePrice: 710, duration: "13h 15m", typical_flights_per_day: 3, countries: { from: "Czech Republic", to: "USA" } },
  { from: "OTP", to: "JFK", airline: "Qatar Airways", airlineCode: "QR", basePrice: 780, duration: "17h 20m", typical_flights_per_day: 3, countries: { from: "Romania", to: "USA" } },
  { from: "OTP", to: "LAX", airline: "Qatar Airways", airlineCode: "QR", basePrice: 880, duration: "21h 0m", typical_flights_per_day: 3, countries: { from: "Romania", to: "USA" } },
  { from: "JNB", to: "JFK", airline: "Qatar Airways", airlineCode: "QR", basePrice: 1150, duration: "20h 45m", typical_flights_per_day: 4, countries: { from: "South Africa", to: "USA" } },
  { from: "JNB", to: "LAX", airline: "Qatar Airways", airlineCode: "QR", basePrice: 1200, duration: "24h 30m", typical_flights_per_day: 4, countries: { from: "South Africa", to: "USA" } },
  { from: "CPT", to: "JFK", airline: "Qatar Airways", airlineCode: "QR", basePrice: 1180, duration: "21h 15m", typical_flights_per_day: 3, countries: { from: "South Africa", to: "USA" } },
  { from: "CAI", to: "JFK", airline: "Qatar Airways", airlineCode: "QR", basePrice: 980, duration: "17h 30m", typical_flights_per_day: 4, countries: { from: "Egypt", to: "USA" } },
  { from: "CAI", to: "LAX", airline: "Qatar Airways", airlineCode: "QR", basePrice: 1080, duration: "21h 15m", typical_flights_per_day: 4, countries: { from: "Egypt", to: "USA" } },
  { from: "CMN", to: "JFK", airline: "Royal Air Maroc", airlineCode: "AT", basePrice: 720, duration: "7h 50m", typical_flights_per_day: 4, countries: { from: "Morocco", to: "USA" } },
  { from: "CMN", to: "LAX", airline: "Qatar Airways", airlineCode: "QR", basePrice: 920, duration: "18h 30m", typical_flights_per_day: 4, countries: { from: "Morocco", to: "USA" } },
  { from: "NBO", to: "JFK", airline: "Qatar Airways", airlineCode: "QR", basePrice: 1100, duration: "19h 45m", typical_flights_per_day: 3, countries: { from: "Kenya", to: "USA" } },
  { from: "NBO", to: "LAX", airline: "Qatar Airways", airlineCode: "QR", basePrice: 1180, duration: "23h 30m", typical_flights_per_day: 3, countries: { from: "Kenya", to: "USA" } },
  { from: "TUN", to: "JFK", airline: "Qatar Airways", airlineCode: "QR", basePrice: 950, duration: "18h 0m", typical_flights_per_day: 3, countries: { from: "Tunisia", to: "USA" } },
  { from: "TUN", to: "LAX", airline: "Qatar Airways", airlineCode: "QR", basePrice: 1050, duration: "21h 45m", typical_flights_per_day: 3, countries: { from: "Tunisia", to: "USA" } },
  { from: "ZNZ", to: "JFK", airline: "Qatar Airways", airlineCode: "QR", basePrice: 1150, duration: "20h 30m", typical_flights_per_day: 3, countries: { from: "Tanzania", to: "USA" } },
  { from: "ZNZ", to: "LAX", airline: "Qatar Airways", airlineCode: "QR", basePrice: 1230, duration: "24h 15m", typical_flights_per_day: 3, countries: { from: "Tanzania", to: "USA" } },
  { from: "ACC", to: "JFK", airline: "Qatar Airways", airlineCode: "QR", basePrice: 1020, duration: "18h 45m", typical_flights_per_day: 3, countries: { from: "Ghana", to: "USA" } },
  { from: "ACC", to: "LAX", airline: "Qatar Airways", airlineCode: "QR", basePrice: 1120, duration: "22h 30m", typical_flights_per_day: 3, countries: { from: "Ghana", to: "USA" } },
  { from: "ABV", to: "JFK", airline: "Qatar Airways", airlineCode: "QR", basePrice: 1050, duration: "19h 15m", typical_flights_per_day: 3, countries: { from: "Nigeria", to: "USA" } },
  { from: "ABV", to: "LAX", airline: "Qatar Airways", airlineCode: "QR", basePrice: 1150, duration: "23h 0m", typical_flights_per_day: 3, countries: { from: "Nigeria", to: "USA" } },
  { from: "NRT", to: "LAX", airline: "Hawaiian Airlines", airlineCode: "HA", basePrice: 820, duration: "11h 30m", typical_flights_per_day: 6, countries: { from: "Japan", to: "USA" } },
  { from: "HND", to: "LAX", airline: "American Airlines", airlineCode: "AA", basePrice: 870, duration: "11h 25m", typical_flights_per_day: 6, countries: { from: "Japan", to: "USA" } },
  { from: "KIX", to: "LAX", airline: "Hawaiian Airlines", airlineCode: "HA", basePrice: 890, duration: "12h 0m", typical_flights_per_day: 5, countries: { from: "Japan", to: "USA" } },
  { from: "ICN", to: "LAX", airline: "Hawaiian Airlines", airlineCode: "HA", basePrice: 850, duration: "12h 15m", typical_flights_per_day: 6, countries: { from: "South Korea", to: "USA" } },
  { from: "PKX", to: "JFK", airline: "Qatar Airways", airlineCode: "QR", basePrice: 1100, duration: "19h 30m", typical_flights_per_day: 1, countries: { from: "China", to: "USA" } },
  { from: "PVG", to: "JFK", airline: "Cathay Pacific", airlineCode: "CX", basePrice: 880, duration: "13h 0m", typical_flights_per_day: 5, countries: { from: "China", to: "USA" } },
  { from: "PVG", to: "LAX", airline: "Cathay Pacific", airlineCode: "CX", basePrice: 880, duration: "13h 0m", typical_flights_per_day: 5, countries: { from: "China", to: "USA" } },
  { from: "CAN", to: "JFK", airline: "Qatar Airways", airlineCode: "QR", basePrice: 1080, duration: "19h 0m", typical_flights_per_day: 4, countries: { from: "China", to: "USA" } },
  { from: "CAN", to: "LAX", airline: "Cathay Pacific", airlineCode: "CX", basePrice: 950, duration: "13h 30m", typical_flights_per_day: 4, countries: { from: "China", to: "USA" } },
  { from: "DEL", to: "JFK", airline: "Qatar Airways", airlineCode: "QR", basePrice: 1050, duration: "18h 45m", typical_flights_per_day: 5, countries: { from: "India", to: "USA" } },
  { from: "DEL", to: "LAX", airline: "Qatar Airways", airlineCode: "QR", basePrice: 1150, duration: "22h 30m", typical_flights_per_day: 5, countries: { from: "India", to: "USA" } },
  { from: "BOM", to: "JFK", airline: "Qatar Airways", airlineCode: "QR", basePrice: 1070, duration: "19h 15m", typical_flights_per_day: 5, countries: { from: "India", to: "USA" } },
  { from: "BOM", to: "LAX", airline: "Qatar Airways", airlineCode: "QR", basePrice: 1170, duration: "23h 0m", typical_flights_per_day: 5, countries: { from: "India", to: "USA" } },
  { from: "SIN", to: "JFK", airline: "Qatar Airways", airlineCode: "QR", basePrice: 1100, duration: "21h 30m", typical_flights_per_day: 5, countries: { from: "Singapore", to: "USA" } },
  { from: "SIN", to: "LAX", airline: "Cathay Pacific", airlineCode: "CX", basePrice: 980, duration: "17h 45m", typical_flights_per_day: 5, countries: { from: "Singapore", to: "USA" } },
  { from: "BKK", to: "JFK", airline: "Qatar Airways", airlineCode: "QR", basePrice: 1080, duration: "22h 15m", typical_flights_per_day: 5, countries: { from: "Thailand", to: "USA" } },
  { from: "BKK", to: "LAX", airline: "Cathay Pacific", airlineCode: "CX", basePrice: 960, duration: "18h 30m", typical_flights_per_day: 5, countries: { from: "Thailand", to: "USA" } },
  { from: "HAN", to: "JFK", airline: "Qatar Airways", airlineCode: "QR", basePrice: 1120, duration: "22h 45m", typical_flights_per_day: 4, countries: { from: "Vietnam", to: "USA" } },
  { from: "HAN", to: "LAX", airline: "Cathay Pacific", airlineCode: "CX", basePrice: 990, duration: "19h 0m", typical_flights_per_day: 4, countries: { from: "Vietnam", to: "USA" } },
  { from: "DPS", to: "JFK", airline: "Qatar Airways", airlineCode: "QR", basePrice: 1200, duration: "24h 30m", typical_flights_per_day: 5, countries: { from: "Indonesia", to: "USA" } },
  { from: "DPS", to: "LAX", airline: "Cathay Pacific", airlineCode: "CX", basePrice: 1050, duration: "20h 45m", typical_flights_per_day: 5, countries: { from: "Indonesia", to: "USA" } },
  { from: "CGK", to: "JFK", airline: "Qatar Airways", airlineCode: "QR", basePrice: 1180, duration: "24h 0m", typical_flights_per_day: 4, countries: { from: "Indonesia", to: "USA" } },
  { from: "CGK", to: "LAX", airline: "Cathay Pacific", airlineCode: "CX", basePrice: 1030, duration: "20h 15m", typical_flights_per_day: 4, countries: { from: "Indonesia", to: "USA" } },
  { from: "MNL", to: "JFK", airline: "Qatar Airways", airlineCode: "QR", basePrice: 1150, duration: "23h 30m", typical_flights_per_day: 4, countries: { from: "Philippines", to: "USA" } },
  { from: "MNL", to: "LAX", airline: "Cathay Pacific", airlineCode: "CX", basePrice: 990, duration: "14h 45m", typical_flights_per_day: 4, countries: { from: "Philippines", to: "USA" } },
  { from: "KUL", to: "JFK", airline: "Qatar Airways", airlineCode: "QR", basePrice: 1130, duration: "23h 0m", typical_flights_per_day: 4, countries: { from: "Malaysia", to: "USA" } },
  { from: "KUL", to: "LAX", airline: "Cathay Pacific", airlineCode: "CX", basePrice: 1000, duration: "18h 30m", typical_flights_per_day: 4, countries: { from: "Malaysia", to: "USA" } },
  { from: "DXB", to: "JFK", airline: "Qatar Airways", airlineCode: "QR", basePrice: 920, duration: "14h 30m", typical_flights_per_day: 5, countries: { from: "United Arab Emirates", to: "USA" } },
  { from: "DXB", to: "LAX", airline: "Qatar Airways", airlineCode: "QR", basePrice: 1000, duration: "18h 15m", typical_flights_per_day: 5, countries: { from: "United Arab Emirates", to: "USA" } },
  { from: "AUH", to: "JFK", airline: "Qatar Airways", airlineCode: "QR", basePrice: 930, duration: "14h 45m", typical_flights_per_day: 4, countries: { from: "United Arab Emirates", to: "USA" } },
  { from: "AUH", to: "LAX", airline: "Qatar Airways", airlineCode: "QR", basePrice: 1010, duration: "18h 30m", typical_flights_per_day: 4, countries: { from: "United Arab Emirates", to: "USA" } },
  { from: "DOH", to: "JFK", airline: "Qatar Airways", airlineCode: "QR", basePrice: 900, duration: "13h 10m", typical_flights_per_day: 5, countries: { from: "Qatar", to: "USA" } },
  { from: "DOH", to: "LAX", airline: "Qatar Airways", airlineCode: "QR", basePrice: 950, duration: "16h 20m", typical_flights_per_day: 5, countries: { from: "Qatar", to: "USA" } },
  { from: "RUH", to: "JFK", airline: "Qatar Airways", airlineCode: "QR", basePrice: 940, duration: "15h 0m", typical_flights_per_day: 4, countries: { from: "Saudi Arabia", to: "USA" } },
  { from: "RUH", to: "LAX", airline: "Qatar Airways", airlineCode: "QR", basePrice: 1020, duration: "18h 45m", typical_flights_per_day: 4, countries: { from: "Saudi Arabia", to: "USA" } },
  { from: "JED", to: "JFK", airline: "Qatar Airways", airlineCode: "QR", basePrice: 950, duration: "15h 15m", typical_flights_per_day: 4, countries: { from: "Saudi Arabia", to: "USA" } },
  { from: "JED", to: "LAX", airline: "Qatar Airways", airlineCode: "QR", basePrice: 1030, duration: "19h 0m", typical_flights_per_day: 4, countries: { from: "Saudi Arabia", to: "USA" } },
  { from: "IST", to: "JFK", airline: "Qatar Airways", airlineCode: "QR", basePrice: 850, duration: "16h 30m", typical_flights_per_day: 5, countries: { from: "Turkey", to: "USA" } },
  { from: "IST", to: "LAX", airline: "Qatar Airways", airlineCode: "QR", basePrice: 950, duration: "20h 15m", typical_flights_per_day: 5, countries: { from: "Turkey", to: "USA" } },
  { from: "AMM", to: "JFK", airline: "Qatar Airways", airlineCode: "QR", basePrice: 920, duration: "16h 0m", typical_flights_per_day: 3, countries: { from: "Jordan", to: "USA" } },
  { from: "AMM", to: "LAX", airline: "Qatar Airways", airlineCode: "QR", basePrice: 1010, duration: "19h 45m", typical_flights_per_day: 3, countries: { from: "Jordan", to: "USA" } },
  { from: "KWI", to: "JFK", airline: "Qatar Airways", airlineCode: "QR", basePrice: 930, duration: "15h 30m", typical_flights_per_day: 3, countries: { from: "Kuwait", to: "USA" } },
  { from: "KWI", to: "LAX", airline: "Qatar Airways", airlineCode: "QR", basePrice: 1020, duration: "19h 15m", typical_flights_per_day: 3, countries: { from: "Kuwait", to: "USA" } },
  { from: "SYD", to: "JFK", airline: "American Airlines", airlineCode: "AA", basePrice: 1300, duration: "21h 30m", typical_flights_per_day: 5, countries: { from: "Australia", to: "USA" } },
  { from: "SYD", to: "LAX", airline: "Qantas", airlineCode: "QF", basePrice: 1250, duration: "15h 5m", typical_flights_per_day: 5, countries: { from: "Australia", to: "USA" } },
  { from: "MEL", to: "JFK", airline: "American Airlines", airlineCode: "AA", basePrice: 1320, duration: "22h 0m", typical_flights_per_day: 4, countries: { from: "Australia", to: "USA" } },
  { from: "MEL", to: "LAX", airline: "Qantas", airlineCode: "QF", basePrice: 1270, duration: "15h 35m", typical_flights_per_day: 4, countries: { from: "Australia", to: "USA" } },
  { from: "AKL", to: "JFK", airline: "American Airlines", airlineCode: "AA", basePrice: 1350, duration: "19h 15m", typical_flights_per_day: 4, countries: { from: "New Zealand", to: "USA" } },
  { from: "AKL", to: "LAX", airline: "American Airlines", airlineCode: "AA", basePrice: 1280, duration: "13h 0m", typical_flights_per_day: 4, countries: { from: "New Zealand", to: "USA" } },
  { from: "NAN", to: "LAX", airline: "Fiji Airways", airlineCode: "FJ", basePrice: 980, duration: "11h 15m", typical_flights_per_day: 3, countries: { from: "Fiji", to: "USA" } },
];
